Repository AdobeDocs/dev-site, pull requests merged in 2020-11, with the labels that each got.

#31 Version 0.0.9
  package.json
Labels: deploy, deploy:dev

#34 Version 0.0.10
  package.json
Labels: deploy:dev

#37 Update dependencies
  README.md
  gatsby-config.js
  package-lock.json
  package.json
Labels: deploy

#38 Update dependencies
  package-lock.json
  package.json
Labels: deploy

#36 Version 0.0.11
  package.json
Labels: deploy:dev
